Repository numerique-gouv/b3desk, pull requests merged in 2023-12, with the labels that each got.

#60 Load schema in callable for it needs an alembic context
  web/migrations/alembic_helpers.py
Labels: bug

#64 Correction additionelle en rapport avec le crash de la dropzone
  web/flaskr/routes.py
Labels: bug

#55 Utilisation de la méthode `url_for` dans les templates
  web/flaskr/templates/brand.html
  web/flaskr/templates/errors/400.html
  web/flaskr/templates/errors/403.html
  web/flaskr/templates/errors/404.html
  web/flaskr/templates/footer.html
  web/flaskr/templates/footer/documentation.html
  web/flaskr/templates/jumbotron.html
  web/flaskr/templates/meeting/files.html
  web/flaskr/templates/meeting/jumbotron.html
  web/flaskr/templates/meeting/list.html
  web/flaskr/templates/meeting/recordings.html
  web/flaskr/templates/meeting/submit.html
  web/flaskr/templates/redirections.html
  web/flaskr/templates/rie.html
  web/flaskr/templates/tools.html
Labels: qualité

#68 Squelette de documentation
  .readthedocs.yaml
  Makefile
  README.md
  documentation/__init__.py
  documentation/conf.py
  documentation/index.rst
  poetry.lock
  pyproject.toml
  web/requirements.doc.txt
Labels: documentation

#69 Utilisation de Github Action pour tester les différentes versions de python et construire la documentation
  .github/workflows/Check_lint.yml
  .github/workflows/Check_local_run.yml
  .github/workflows/Documentation.yml
  .github/workflows/Test_coverage.yml
Labels: documentation, tests

#70 Utilisation de `diff-cover` dans le job de couverture de code de GHA
  .github/workflows/Test_coverage.yml
Labels: tests

#73 Documentation : revue de code
  documentation/_static/ci.png
  documentation/conf.py
  documentation/developers/ci.md
  documentation/developers/dockerPersistence.md
  documentation/developers/index.rst
  documentation/developers/translation.md
  documentation/index.rst
  documentation/maintainers/index.rst
  documentation/maintainers/meetingFiles.md
  documentation/maintainers/pullRequestValidation.md
Labels: documentation

#65 Lecture de la configuration avec pydantic-settings, et documentation
  documentation/conf.py
  documentation/maintainers/index.rst
  documentation/maintainers/settings.rst
  poetry.lock
  pyproject.toml
  web.env.example
  web/Dockerfile
  web/Dockerfile-tests
  web/flaskr/__init__.py
  web/flaskr/constants.py
  web/flaskr/models.py
  web/flaskr/settings.py
  web/flaskr/utils.py
  web/instance/config.py
  web/requirements.doc.txt
  web/tests/conftest.py
  web/tests/meeting/test_meeting.py
Labels: documentation, fonctionnalité

#66 La balise HTML `<title>` est lue depuis la configuration sur toutes les pages
  web/b3desk/routes.py
  web/b3desk/templates/layout.html
  web/b3desk/templates/static-layout.html
Labels: bug
